### ISSUE TITLE
Change the package name so it doesn't conflict with harmony-py

### ISSUE THREAD

**Issue by danielfromearth** [nasa/harmony-service-lib-py#44]
Regarding ticket [HARMONY-1781](https://bugs.earthdata.nasa.gov/browse/HARMONY-1781) and [a Slack discussion](https://eosdis.slack.com/archives/C01DC2R2TRR/p1715969006447109).

Change the package name to `harmony_service_lib`.

**Comment by vinnyinverso** [comment]
This is in the latest release, thanks @danielfromearth!
